'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMUI6.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _7zip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7zip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _me() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("me", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property CEF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CEF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ChatGPT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChatGPT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Copilot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copilot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property csvhelper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csvhelper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property DarkUI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DarkUI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property default_package_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("default-package-icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property dropbox() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("dropbox", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property dropbox1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dropbox1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property fandom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fandom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Gitee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gitee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Github() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Github", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Jsonnet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jsonnet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Magick_NET() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magick.NET", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ModDrop_White32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ModDrop-White32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property NEXUS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEXUS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Outlook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Outlook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property payhip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payhip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Paypal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paypal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property QQQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QQQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property SMAPI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SMAPI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Stardew_Valley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stardew Valley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Steam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Steam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property SunnyUI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SunnyUI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property WebView2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WebView2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 上传() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("上传", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 上传云() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("上传云", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 上箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("上箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 下箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("下箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 下载() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("下载", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 下载文件夹() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("下载文件夹", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 代码文件夹() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("代码文件夹", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 保存() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("保存", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 全选() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("全选", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 六个点() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("六个点", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 农场布局规划器() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("农场布局规划器", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 切换() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("切换", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 删除() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("删除", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 刷新() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("刷新", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 加号() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("加号", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 叉号() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("叉号", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 右箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("右箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 呵呵鱼MOD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("呵呵鱼MOD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 哔哩哔哩() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("哔哩哔哩", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 存档进度检查器() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("存档进度检查器", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 存档预测器() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("存档预测器", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 左箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("左箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 数据切换() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("数据切换", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 数据库() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("数据库", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 文件夹() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("文件夹", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 文字大小() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("文字大小", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 模块() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("模块", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似     (function() {
        '''        document.addEventListener(&apos;DOMContentLoaded&apos;, (event) =&gt; {
        '''            // 检测暗黑模式
        '''            function detectDarkMode() {
        '''                if (window.matchMedia &amp;&amp; window.matchMedia(&apos;(prefers-color-scheme: dark)&apos;).matches) {
        '''                    return true;
        '''                }
        '''                return false;
        '''            }
        '''
        '''            // 应用通用暗黑模式样式
        '''            function applyGenericDarkMode() {
        '''                const style = document.createElement(&apos;style&apos;);
        '''                sty [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 浏览器脚本() As String
            Get
                Return ResourceManager.GetString("浏览器脚本", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 添加带圆圈() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("添加带圆圈", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 爱发电() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("爱发电", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {\rtf1\adeflang1025\ansi\ansicpg936\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe2052\themelang1033\themelangfe2052\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f13\fbidi \fnil\fcharset134\fprq2{\*\panose 02010600030101010101}\&apos;cb\&apos;ce\&apos;cc\&apos;e5{\*\falt SimSun};}{\f15\fbidi \fmodern\fcharset128\fprq1{\*\panose 020b0609070205080204}MS Gothic{\*\falt ?? ????};}
        '''{\f34\fbidi \froman\fcharset0\fprq2{\*\pan [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 用户许可协议() As String
            Get
                Return ResourceManager.GetString("用户许可协议", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 移动() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("移动", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 试验() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("试验", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 颜色滤镜() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("颜色滤镜", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 StardewValleyGamePath=
        '''LocalRepositoryPath=
        '''StardewValleyGameBackupPath=
        '''VisualStudioCodeEXE=
        '''VisualStudioEXE=
        '''DisplayLanguage=
        '''NewsLanguage=
        '''NewsSever=
        '''UpdateSever=
        '''AlternativeUpdateSever=No Use
        '''NexusAPI=
        '''GiteeToken=
        '''GithubToken=
        '''LaunchSelection=1
        '''LaunchParameters=
        '''CustomLaunchCMD=
        '''SaveUserWindowSize=True
        '''MainWindowWidth=1280
        '''MainWindowHeight=720
        '''AutoGetNews=True
        '''SaveNewsInTodayUse=False
        '''AutoCheckUpdate=True
        '''AutoStartDownloadUpdate=True
        '''AdminDragDropPatch=True
        '''AutoSelectFirstNexusDo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property 默认设置文件() As String
            Get
                Return ResourceManager.GetString("默认设置文件", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
